sonar.cpd.exclusions=\
  client/eslint.config.js,\
  test.sh,\
  client/src/components/charts/ExecutionsByOrgChart.tsx,\
  client/src/components/charts/ResourceTrendChart.tsx,\
  client/src/components/reports/UsageCharts.tsx,\
  client/src/pages/ROIReports.tsx,\
  client/src/pages/diagnostics/components/MemoryChart.tsx
